FROM mcr.microsoft.com/dotnet/aspnet::3.1
WORKDIR /usr/local/app/

RUN apt-get update \
    && apt-get install -y curl apt-utils libgdiplus libc6-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -Ls https://github.com/block-core/blockcore-explorer/releases/download/#{VERSION}#/Blockcore.Explorer-#{VERSION}#-linux-x64.tar.gz \
    | tar -xvz -C .

EXPOSE 9911
ENTRYPOINT ["dotnet", "Blockcore.Explorer.dll"]
